/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codigo;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis David
 */
public class Ansiedad extends javax.swing.JPanel {

    /**
     * Creates new form Ansiedad
     */
    public Registrar registrar = new Registrar();
    public Puntuacion puntu = new Puntuacion();
    String nombre;
    public Ansiedad() {
        initComponents();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAnsiedad = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botonTest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setForeground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAnsiedad.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Ansiedad");

        jButton2.setBackground(new java.awt.Color(255, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Estres");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Depresion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Ansiedad");

        botonTest.setBackground(new java.awt.Color(255, 204, 255));
        botonTest.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonTest.setText("Realizar Test");
        botonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTestActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("La ansiedad es una experiencia emocional que todos estamos \nfamiliarizados con ella, pero no por eso fácil de definir. \nLa ansiedad es un fenómeno normal que lleva al conocimiento del\npropio ser, que moviliza las operaciones defensivas del organismo,\nes base para el aprendizaje, estimula el desarrollo de la \npersonalidad, motiva el logro de metas y contribuye a mantener  \nun elevado nivel de trabajo y conducta. En exceso, la ansiedad es\nnociva, maladaptativa, compromete la eficacia y conduce a las\nenfermedades. En su uso cotidiano el término ansiedad puede\nsignificar un ánimo transitorio de tensión (sentimiento), un\nreflejo de la toma de conciencia de un peligro (miedo), un deseo\nintenso (anhelo), una respuesta fisiológica ante una demanda \n(estrés) y un estado de sufrimiento mórbido(trastorno de ansiedad).");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelAnsiedadLayout = new javax.swing.GroupLayout(panelAnsiedad);
        panelAnsiedad.setLayout(panelAnsiedadLayout);
        panelAnsiedadLayout.setHorizontalGroup(
            panelAnsiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnsiedadLayout.createSequentialGroup()
                .addGroup(panelAnsiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnsiedadLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(3, 3, 3)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAnsiedadLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelAnsiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonTest)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(206, 206, 206))
        );
        panelAnsiedadLayout.setVerticalGroup(
            panelAnsiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnsiedadLayout.createSequentialGroup()
                .addGroup(panelAnsiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(botonTest)
                .addGap(29, 29, 29))
        );

        add(panelAnsiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Estres e1 = new Estres();
        e1.setSize(690,540);
        e1.setLocation(0,0);
        panelAnsiedad.repaint();
        panelAnsiedad.removeAll();
        panelAnsiedad.add(e1,BorderLayout.CENTER);
        panelAnsiedad.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Depresion d1 = new Depresion();
        d1.setSize(690,540);
        d1.setLocation(0,0);
        
        panelAnsiedad.repaint();
        panelAnsiedad.removeAll();
        panelAnsiedad.add(d1,BorderLayout.CENTER);
        panelAnsiedad.revalidate();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTestActionPerformed
        TestA test = new TestA();
        JOptionPane.showMessageDialog(null, "Realiza el test cuidadosamente: " + getNombre());
        test.setCuenta(getNombre());
        test.setVisible(true);
        panelAnsiedad.repaint();
        panelAnsiedad.removeAll();
        panelAnsiedad.add(panelAnsiedad, BorderLayout.CENTER);
        panelAnsiedad.revalidate();

    }//GEN-LAST:event_botonTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelAnsiedad;
    // End of variables declaration//GEN-END:variables


}
