/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codigo;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis David
 */
public class Depresion extends javax.swing.JPanel {

    /**
     * Creates new form Depresion
     */
    public Registrar registrar = new Registrar();
    public Puntuacion puntu = new Puntuacion();
    String nombre;
    public Depresion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDepresion = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonTest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDepresion.setBackground(new java.awt.Color(204, 255, 255));

        jButton2.setBackground(new java.awt.Color(255, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Estres");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Depresion");

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Ansiedad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Depresion");

        botonTest.setBackground(new java.awt.Color(255, 204, 255));
        botonTest.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonTest.setText("Realizar Test");
        botonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTestActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Las depresiones son un grupo heterogéneo de trastornos \nafectivos que se caracterizan por un estado de ánimo \ndeprimido, disminución del disfrute, apatía y pérdida del \ninterés en el trabajo, sentimientos de minusvalía, insomnio,\nanorexia e ideación suicida. A menudo presenta ansiedad y\nsíntomas somáticos variados. La depresión es un sentimiento\nde tristeza intenso, que puede producirse tras una pérdida\nreciente y otro hecho triste, pero es desproporcionado con\nrespecto a la magnitud del hecho y persiste más allá de un\nperíodo justificado.Se estima que el 10% de la gente que\nconsulta al médico pensando que tiene un problema físico,\ntiene en realidad\nuna depresión.\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelDepresionLayout = new javax.swing.GroupLayout(panelDepresion);
        panelDepresion.setLayout(panelDepresionLayout);
        panelDepresionLayout.setHorizontalGroup(
            panelDepresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepresionLayout.createSequentialGroup()
                .addGroup(panelDepresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDepresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelDepresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDepresionLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(3, 3, 3)
                                .addComponent(jButton3)
                                .addGap(4, 4, 4)
                                .addComponent(jButton1))
                            .addGroup(panelDepresionLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(botonTest))))
                    .addGroup(panelDepresionLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(229, 229, 229))
        );
        panelDepresionLayout.setVerticalGroup(
            panelDepresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepresionLayout.createSequentialGroup()
                .addGroup(panelDepresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(botonTest)
                .addGap(35, 35, 35))
        );

        add(panelDepresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Estres e1 = new Estres();
        e1.setSize(690,540);
        e1.setLocation(0,0);
        
        panelDepresion.removeAll();
        panelDepresion.add(e1,BorderLayout.CENTER);
        panelDepresion.revalidate();
        panelDepresion.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ansiedad a1 = new Ansiedad();
        a1.setSize(690,540);
        a1.setLocation(0,0);
        
        panelDepresion.removeAll();
        panelDepresion.add(a1,BorderLayout.CENTER);
        panelDepresion.revalidate();
        panelDepresion.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTestActionPerformed
        TestA test = new TestA();
        JOptionPane.showMessageDialog(null, "Realiza el test cuidadosamente: " + getNombre());
        test.setCuenta(getNombre());
        test.setVisible(true);
        panelDepresion.repaint();
        panelDepresion.removeAll();
        panelDepresion.add(panelDepresion, BorderLayout.CENTER);
        panelDepresion.revalidate();
    }//GEN-LAST:event_botonTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelDepresion;
    // End of variables declaration//GEN-END:variables
}
