/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package codigo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis David
 */
public class TestA extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Conexion conexi = new Conexion();
    public PreparedStatement ps;
    public ResultSet rs;
    public DefaultTableModel dft;
    public int i = 1;
    public ButtonGroup grupo1;
    public int contadorS;
    public int contador = 0;
    public String cuenta;
    public JLabel Dato = new JLabel("");
    
    public TestA() {
        initComponents();
        crearGrupo();
        this.setLocationRelativeTo(null);
    }

    public String getCuenta() {
        return cuenta;
    }

    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        opcion1 = new javax.swing.JRadioButton();
        opcion2 = new javax.swing.JRadioButton();
        opcion3 = new javax.swing.JRadioButton();
        opcion4 = new javax.swing.JRadioButton();
        botonSi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaEs = new javax.swing.JTextArea();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ito.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 490, -1, 89));

        jLabel3.setFont(new java.awt.Font("Rockwell", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Test de Beck");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tec.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 506, -1, -1));

        botonSalir.setBackground(new java.awt.Color(204, 255, 255));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 0, 89, 27));

        opcion1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        opcion1.setForeground(new java.awt.Color(0, 0, 0));
        opcion1.setText("sdfdfsd");
        opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion1ActionPerformed(evt);
            }
        });
        jPanel1.add(opcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 167, -1, 56));

        opcion2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        opcion2.setForeground(new java.awt.Color(0, 0, 0));
        opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion2ActionPerformed(evt);
            }
        });
        jPanel1.add(opcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 241, -1, 55));

        opcion3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        opcion3.setForeground(new java.awt.Color(0, 0, 0));
        opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion3ActionPerformed(evt);
            }
        });
        jPanel1.add(opcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 316, -1, 60));

        opcion4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        opcion4.setForeground(new java.awt.Color(0, 0, 0));
        opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion4ActionPerformed(evt);
            }
        });
        jPanel1.add(opcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 388, -1, 55));

        botonSi.setText("jButton1");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });
        jPanel1.add(botonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 441, 119, 43));

        jLabel5.setBackground(new java.awt.Color(204, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kpi.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 67, -1, 85));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 50, -1, -1));

        areaEs.setColumns(20);
        areaEs.setFont(new java.awt.Font("Sitka Display", 3, 16)); // NOI18N
        areaEs.setRows(5);
        areaEs.setText("Señale cual de las afirmaciones de cada grupo\ndescribe mejor como se ha sentido durante esta \núltima semana. ");
        areaEs.setAutoscrolls(false);
        areaEs.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(areaEs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 67, 356, 75));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        creandoOpciones();
    }

    private void opcion1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        botonSi.setEnabled(true);
        opcion2.setEnabled(false);
        opcion3.setEnabled(false);
        opcion4.setEnabled(false);
        
    }

    private void opcion2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        botonSi.setEnabled(true);
        opcion1.setEnabled(false);
        opcion3.setEnabled(false);
        opcion4.setEnabled(false);
    }

    private void opcion3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        botonSi.setEnabled(true);
        opcion1.setEnabled(false);
        opcion2.setEnabled(false);
        opcion4.setEnabled(false);

    }

    private void opcion4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        botonSi.setEnabled(true);
        opcion1.setEnabled(false);
        opcion2.setEnabled(false);
        opcion3.setEnabled(false);
    }

    private ButtonGroup crearGrupo() {
        grupo1 = new ButtonGroup();
        grupo1.add(opcion1);
        grupo1.add(opcion2);
        grupo1.add(opcion3);
        grupo1.add(opcion4);
        creandoOpciones();
        editarArea();
        return grupo1;
    }

    public void seleccionBoto() {

        if (opcion1.isSelected())
        {

            JOptionPane.showMessageDialog(null, "0");
            contador += 0;
        } else if (opcion2.isSelected())
        {

            JOptionPane.showMessageDialog(null, "1");
            contador += 1;
        } else if (opcion3.isSelected())
        {

            JOptionPane.showMessageDialog(null, "2");
            contador += 2;
        } else if (opcion4.isSelected())
        {
            JOptionPane.showMessageDialog(null, "3");
            contador += 3;
        }
        JOptionPane.showMessageDialog(null, "Puntuación actual: " + contador);

    }

    public void editarArea() {
        areaEs.setEditable(false);
    }

    public void creandoOpciones() {
        opcion1.setEnabled(true);
        opcion2.setEnabled(true);
        opcion3.setEnabled(true);
        opcion4.setEnabled(true);
        botonSi.setEnabled(false);

        seleccionBoto();
        switch (i)
        {
            case 1:
                
                opcion1.setText("No me siento triste");
                opcion2.setText("Me siento triste.");
                opcion3.setText("Me siento triste continuamente y no puedo dejar de estarlo.");
                opcion4.setText("Me siento tan triste o tan desgraciado que no puedo soportarlo.");
                i++;
                botonSi.setText("Siguiente");
                break;

            case 2:
                grupo1.clearSelection();
                opcion1.setText("No me siento especialmente desanimado respecto al futuro.");
                opcion2.setText("Me siento desanimado respecto al futuro.");
                opcion3.setText("Siento que no tengo que esperar nada.");
                opcion4.setText("Siento que el futuro es desesperanzador y las cosas no mejorarán.");
                i++;
                break;

            case 3:
                grupo1.clearSelection();
                opcion1.setText("No me siento fracasado.");
                opcion2.setText("Creo que he fracasado más que la mayoría de las personas.");
                opcion3.setText("Cuando miro hacia atrás, sólo veo fracaso tras fracaso.");
                opcion4.setText("Me siento una persona totalmente fracasada.");
                i++;
                break;

            case 4:
                grupo1.clearSelection();
                opcion1.setText("Las cosas me satisfacen tanto como antes.");
                opcion2.setText("No disfruto de las cosas tanto como antes.");
                opcion3.setText("Ya no obtengo una satisfacción auténtica de las cosas.");
                opcion4.setText("Estoy insatisfecho o aburrido de todo.");
                i++;
                break;

            case 5:
                grupo1.clearSelection();
                opcion1.setText("No me siento especialmente culpable.");
                opcion2.setText("Me siento culpable en bastantes ocasiones.");
                opcion3.setText("Me siento culpable en la mayoría de las ocasiones.");
                opcion4.setText("Me siento culpable constantemente.");
                i++;
                break;

            case 6:
                grupo1.clearSelection();
                opcion1.setText("No creo que esté siendo castigado.");
                opcion2.setText("Me siento como si fuese a ser castigado.");
                opcion3.setText("Espero ser castigado.");
                opcion4.setText("Siento que estoy siendo castigado.");
                i++;
                break;

            case 7:
                grupo1.clearSelection();
                opcion1.setText("No estoy decepcionado de mí mismo.");
                opcion2.setText("Estoy decepcionado de mí mismo.");
                opcion3.setText("Me da vergüenza de mí mismo.");
                opcion4.setText("Me detesto.");
                i++;
                break;

            case 8:
                grupo1.clearSelection();
                opcion1.setText("No me considero peor que cualquier otro.");
                opcion2.setText("Me autocritico por mis debilidades o por mis errores.");
                opcion3.setText("Continuamente me culpo por mis faltas.");
                opcion4.setText("Me culpo por todo lo malo que sucede.");
                i++;
                break;

            case 9:
                grupo1.clearSelection();
                opcion1.setText("No tengo ningún pensamiento de suicidio.");
                opcion2.setText("A veces pienso en suicidarme, pero no lo cometería.");
                opcion3.setText("Desearía suicidarme.");
                opcion4.setText("Me suicidaría si tuviese la oportunidad.");
                i++;
                break;

            case 10:
                grupo1.clearSelection();
                opcion1.setText("No lloro más de lo que solía llorar.");
                opcion2.setText("Ahora lloro más que antes.");
                opcion3.setText("Lloro continuamente.");
                opcion4.setText("Antes era capaz de llorar, pero ahora no puedo.");
                i++;
                break;

            case 11:
                grupo1.clearSelection();
                opcion1.setText("No estoy más irritado de lo normal en mí.");
                opcion2.setText("Me molesto o irrito más fácilmente que antes.");
                opcion3.setText("Me siento irritado continuamente.");
                opcion4.setText("No me irrito absolutamente nada.");
                i++;
                break;
            case 12:
                grupo1.clearSelection();
                opcion1.setText("No he perdido el interés por los demás.");
                opcion2.setText("Estoy menos interesado en los demás que antes.");
                opcion3.setText("He perdido la mayor parte de mi interés por los demás.");
                opcion4.setText("He perdido todo el interés por los demás.");
                i++;
                break;

            case 13:
                grupo1.clearSelection();
                opcion1.setText("Tomo decisiones más o menos como siempre he hecho.");
                opcion2.setText("Evito tomar decisiones más que antes.");
                opcion3.setText("Tomar decisiones me resulta mucho más difícil que antes.");
                opcion4.setText("Ya me es imposible tomar decisiones.");
                i++;
                break;

            case 14:
                grupo1.clearSelection();
                opcion1.setText("No creo tener peor aspecto que antes.");
                opcion2.setText("Me temo que ahora parezco más viejo o poco atractivo.");
                opcion3.setText("Creo que se han producido cambios permanentes en mi aspecto.");
                opcion4.setText("Creo que tengo un aspecto horrible.");
                i++;
                break;

            case 15:
                grupo1.clearSelection();
                opcion1.setText("Trabajo igual que antes.");
                opcion2.setText("Me cuesta un esfuerzo extra comenzar a hacer algo.");
                opcion3.setText("Tengo que obligarme mucho para hacer algo.");
                opcion4.setText("No puedo hacer nada en absoluto.");
                i++;
                break;

            case 16:
                grupo1.clearSelection();
                opcion1.setText("Duermo tan bien como siempre.");
                opcion2.setText("No duermo tan bien como antes.");
                opcion3.setText("Me despierto una o dos horas antes de lo habitual.");
                opcion4.setText("Me despierto varias horas antes de lo habitual.");
                i++;
                break;

            case 17:
                grupo1.clearSelection();
                opcion1.setText("No me siento más cansado de lo normal.");
                opcion2.setText("Me canso más fácilmente que antes.");
                opcion3.setText("Me canso en cuanto hago cualquier cosa.");
                opcion4.setText("Estoy demasiado cansado para hacer nada.");
                i++;
                break;

            case 18:
                grupo1.clearSelection();
                opcion1.setText("Mi apetito no ha disminuido.");
                opcion2.setText("No tengo tan buen apetito como antes.");
                opcion3.setText("Ahora tengo mucho menos apetito.");
                opcion4.setText("He perdido completamente el apetito.");
                i++;
                break;

            case 19:
                grupo1.clearSelection();
                opcion1.setText("Últimamente he perdido poco peso o no he perdido nada.");
                opcion2.setText("He perdido más de 2 kilos y medio.");
                opcion3.setText("He perdido más de 4 kilos.");
                opcion4.setText("He perdido más de 7 kilos.");
                i++;
                break;

            case 20:
                grupo1.clearSelection();
                opcion1.setText("No estoy preocupado por mi salud más de lo normal.");
                opcion2.setText("Estoy preocupado por problemas físicos como dolores, molestias.");
                opcion3.setText("Estoy preocupado por mis problemas físicos.");
                opcion4.setText("Estoy tan preocupado por mis problemas físicos que soy incapaz de pensar");
                i++;
                break;

            case 21:
                grupo1.clearSelection();
                opcion1.setText("No he observado ningún cambio reciente en mi interés.");
                opcion2.setText("Estoy menos interesado por el sexo que antes.");
                opcion3.setText("Estoy mucho menos interesado por el sexo.");
                opcion4.setText("He perdido totalmente mi interés por el sexo.");
                i++;
                break;

            default:
                botonSi.setEnabled(false);
                opcion1.setEnabled(false);
                opcion2.setEnabled(false);
                opcion3.setEnabled(false);
                opcion4.setEnabled(false);
                try

                {
                    JOptionPane.showMessageDialog(null, getCuenta());
                    Conexion con = new Conexion();
                    Connection conexion = con.getConnection();
                    ps = conexion.prepareStatement("update usuario set puntuacion=? where usuario=?");
                    ps.setString(1, Integer.toString(contador));
                    ps.setString(2, getCuenta());
                    int resultado = ps.executeUpdate();
                    if ((resultado > 0))
                    {
                        JOptionPane.showMessageDialog(null, "Datos actualizados");

                    } else
                    {
                        JOptionPane.showMessageDialog(null, "No fue posible actualizar los datos");
                    }
                    conexion.close();
                } catch (Exception e)
                {
                    System.err.println(e);
                }
                if (contador > 0 && contador < 11)
                {
                    JOptionPane.showMessageDialog(null, "Su valoración es: Estos altibajos son considerados normales.");

                } else if (10 < contador && contador < 17)
                {
                    JOptionPane.showMessageDialog(null, "Su valoración es: Leve perturbación del estado de ánimo.");
                } else if (16 > contador && contador < 21)
                {
                    JOptionPane.showMessageDialog(null, "Su valoración es: Estados de depresión intermitentes.");

                } else if (contador > 20 && contador < 31)
                {
                    JOptionPane.showMessageDialog(null, "Su valoración es: Depresión moderada.");
                } else if (contador > 30 && contador < 41)
                {
                    JOptionPane.showMessageDialog(null, "Su valoración es: Depresión grave.");

                } else if (contador > 39)
                {
                    JOptionPane.showMessageDialog(null, "Su valoración es: Depresión extrema.");
                }
                break;

        }

    }
    //private void 

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify                     
    private javax.swing.JTextArea areaEs;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opcion1;
    private javax.swing.JRadioButton opcion2;
    private javax.swing.JRadioButton opcion3;
    private javax.swing.JRadioButton opcion4;
    // End of variables declaration                   
}
