/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

import java.awt.BorderLayout;
import static java.awt.GridBagConstraints.BOTH;
import java.awt.Image;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Luis David
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public Registrar registrar = new Registrar();
    public Puntuacion puntu = new Puntuacion();
    String nombre;
    
    private ImageIcon imagen;
    private Icon icono;
    
            
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Tamano absolutodeImagen
        //this.setExtendedState(MAXIMIZED_BOTH);
        
        //PintarELLogo
        this.pintarImagen(this.logo,"src/recursos/Logo-flor-de-loto.png");
       
        
        
    }
    
        public String getNombre() {
        return nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        barraDeTareas = new javax.swing.JPanel();
        presentacion = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        navegacion = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        barraDeTareas.setBackground(new java.awt.Color(0, 0, 0));
        barraDeTareas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(barraDeTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 20));

        presentacion.setBackground(new java.awt.Color(255, 255, 255));
        presentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Logo-flor-de-loto.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(40, 40));
        presentacion.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        getContentPane().add(presentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 860, 40));

        navegacion.setBackground(new java.awt.Color(255, 204, 255));
        navegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/IconoApoyo.png"))); // NOI18N
        jButton1.setText("Apoyo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        navegacion.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/IconoHome.png"))); // NOI18N
        jButton2.setText("Inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        navegacion.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        getContentPane().add(navegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 540));

        contenido.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 690, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ApoyoEmocional a1 = new ApoyoEmocional();
        a1.setSize(540,690);
        a1.setLocation(0,0);
        contenido.removeAll();
        contenido.add(a1,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }
    
    private void pintarImagen(JLabel lbl,String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono =  new ImageIcon(this.imagen.getImage());
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_DEFAULT
        )
    );
        lbl.setIcon(this.icono);
        this.repaint();

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraDeTareas;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel contenido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel navegacion;
    private javax.swing.JPanel presentacion;
    // End of variables declaration//GEN-END:variables
}
